# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='first_name',
        ),
    ]
